services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    ports:
      - "42069:42069"
    environment:
      - ISPONSORBLOCKTV_PORT=42069
    volumes:
      - /PATH_TO_YOUR_DATA_DIR:/app/data
