services:
  isponsorblocktv:
    image: isponsorblocktv-web
    build: .
    container_name: isponsorblocktv-web
    restart: unless-stopped
    ports:
      - "42069:42069"
    environment:
      - ISPONSORBLOCKTV_PORT=42069
    volumes:
      - ./data:/app/data
    # This command ensures we start the Web Interface, not the old CLI tool
    command: python -m iSponsorBlockTV.web
